spring.application.name=billing
# Server Port
server.port=8080

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_billing
spring.datasource.username=w.a.paramithkavisha
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true




## ?? Step 3: Run the Project in IntelliJ

### Option A ? Green Play Button (Easiest!)

Top Right Corner ? Click ? Green Play Button


### Option B ? Right Click

src/main/java/com/restaurant/billing/
??? BillingApplication.java ? Right click ? Run 'BillingApplication'


### Option C ? Terminal inside IntelliJ

View ? Tool Windows ? Terminal
